.TH argparse-manpage "1" Manual
.SH NAME
argparse-manpage
.SH SYNOPSIS
.B argparse-manpage
[-h] [--logdir [logdir]] [--comment [comment]] [--loglevel [loglevel]] [--compress [compress]] parameters
.SH DESCRIPTION
Launch run from a json file
.SH OPTIONS
.TP
\fBparameters\fR
parameter json file

.TP
\fB\-\-logdir\fR [logdir]
log file

.TP
\fB\-\-comment\fR [comment]
comments on the run

.TP
\fB\-\-loglevel\fR [loglevel]
log level

.TP
\fB\-\-compress\fR [compress]
log level

.SH AUTHORS
.B metadynamic
was written by R.Plasson <raphael.plasson@univ\-avignon.fr>.
.SH DISTRIBUTION
The latest version of metadynamic may be downloaded from
.UR <<UNSET \-\-url OPTION>>
.UE
