sudo: false

language:
  - python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - pycodestyle --max-line-length 128 metadynamic
  - pytest --verbose --capture=no metadynamic
  - pip install .

notifications:
  email: false
