.TH metarun "1" Manual
.SH NAME
metarun
.SH SYNOPSIS
.B metarun
[-h] [-c comment] [-d logdir] [-l log_level] [-x compress_level] param_file
.SH DESCRIPTION
Launch a metadynamic run from a json or hdf5 file (metadynamic v1.0.0).
.SH OPTIONS
.TP
\fBparam_file\fR
parameter json file, or previous hdf5 result file

.TP
\fB\-c\fR comment, \fB\-\-comment\fR comment
run comment string

.TP
\fB\-d\fR logdir, \fB\-\-logdir\fR logdir
Directory for saving log text files (if set, will override the value from
.br
param_file)

.TP
\fB\-l\fR log_level, \fB\-\-loglevel\fR log_level
Logging level: DEBUG, INFO, WARNING, ERROR (if set, will override the value
.br
from param_file)

.TP
\fB\-x\fR compress_level, \fB\-\-compress\fR compress_level
compression level for the hdf5 output file

.SH AUTHORS
.B metadynamic
was written by R.Plasson <raphael.plasson@univ\-avignon.fr>.
.SH DISTRIBUTION
The latest version of metadynamic may be downloaded from
.UR <<UNSET \-\-url OPTION>>
.UE
